#!/usr/bin/env bash
# enroll-agent.sh — OSEye agent enrollment
#
# Fetches the CA certificate from the server, generates an agent key + CSR,
# gets the cert signed by the server, and writes /etc/oseye/agent.env.
# Requires: openssl, curl, python3 (all standard on Debian/Ubuntu/RHEL).
#
# Usage:
#   OSEYE_SERVER=<host>:<api-port> OSEYE_TOKEN=<token> sudo bash enroll-agent.sh
#
# Optional overrides:
#   OSEYE_CERTS_DIR   (default: /etc/oseye/certs)
#   OSEYE_AGENT_ENV   (default: /etc/oseye/agent.env)
#   OSEYE_AGENT_ID    (default: auto-generated UUID)
#   OSEYE_GRPC_PORT   (default: 50051)

set -euo pipefail

: "${OSEYE_SERVER:?ERROR: OSEYE_SERVER must be set (e.g. myserver.example.com:8000)}"
: "${OSEYE_TOKEN:?ERROR: OSEYE_TOKEN must be set}"

CERTS_DIR="${OSEYE_CERTS_DIR:-/etc/oseye/certs}"
AGENT_ENV="${OSEYE_AGENT_ENV:-/etc/oseye/agent.env}"
GRPC_PORT="${OSEYE_GRPC_PORT:-50051}"
AGENT_HOSTNAME=$(hostname -f 2>/dev/null || hostname)

# Derive server host (strip port if present)
SERVER_HOST="${OSEYE_SERVER%%:*}"
API_BASE="https://${OSEYE_SERVER}"

# Auto-generate agent ID if not provided
if [[ -z "${OSEYE_AGENT_ID:-}" ]]; then
    if [[ -r /proc/sys/kernel/random/uuid ]]; then
        OSEYE_AGENT_ID=$(cat /proc/sys/kernel/random/uuid)
    else
        OSEYE_AGENT_ID=$(python3 -c "import uuid; print(uuid.uuid4())")
    fi
fi

echo "==> OSEye Agent Enrollment"
echo "    Server   : $OSEYE_SERVER"
echo "    Hostname : $AGENT_HOSTNAME"
echo "    Agent ID : $OSEYE_AGENT_ID"
echo ""

# ── Create directories ────────────────────────────────────────────────────────
install -d -m 700 "$CERTS_DIR"
install -d -m 700 "$(dirname "$AGENT_ENV")"

# ── Step 1: Fetch CA certificate (TOFU — Trust On First Use) ─────────────────
# The server's TLS cert is signed by the OSEye CA, which is not yet trusted on
# this host. We use --insecure ONLY for this first request to bootstrap trust.
# All subsequent requests use --cacert to enforce certificate verification.
echo "==> Fetching CA certificate (TOFU)..."
curl --fail --silent --insecure \
    --output "$CERTS_DIR/ca.crt" \
    "${API_BASE}/api/v1/enroll/${OSEYE_TOKEN}"
chmod 644 "$CERTS_DIR/ca.crt"
echo "    Saved to $CERTS_DIR/ca.crt"

# ── Step 2: Generate agent private key and CSR ────────────────────────────────
echo "==> Generating agent key and CSR..."
openssl genrsa -out "$CERTS_DIR/agent.key" 2048 2>/dev/null
chmod 600 "$CERTS_DIR/agent.key"

CSR_PEM=$(openssl req -new \
    -key "$CERTS_DIR/agent.key" \
    -subj "/CN=${AGENT_HOSTNAME}/O=OSEye/C=FR" \
    2>/dev/null)

# ── Step 3: POST CSR to server for signing ────────────────────────────────────
echo "==> Submitting CSR for signing..."
# Escape the CSR PEM for JSON embedding (replace newlines with \n)
CSR_JSON=$(echo "$CSR_PEM" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))")
HOSTNAME_JSON=$(python3 -c "import json; print(json.dumps('${AGENT_HOSTNAME}'))")

RESPONSE=$(curl --fail --silent \
    --cacert "$CERTS_DIR/ca.crt" \
    --request POST \
    --header "Content-Type: application/json" \
    --data "{\"csr\": ${CSR_JSON}, \"hostname\": ${HOSTNAME_JSON}}" \
    "${API_BASE}/api/v1/enroll/${OSEYE_TOKEN}")

# Extract cert field from {"cert": "<PEM>"}
echo "$RESPONSE" | python3 -c "
import sys, json
data = json.load(sys.stdin)
if 'cert' not in data:
    print('ERROR: unexpected response:', data, file=sys.stderr)
    sys.exit(1)
print(data['cert'], end='')
" > "$CERTS_DIR/agent.crt"
chmod 644 "$CERTS_DIR/agent.crt"
echo "    Saved to $CERTS_DIR/agent.crt"

# ── Step 4: Write agent.env ───────────────────────────────────────────────────
echo "==> Writing $AGENT_ENV..."
cat > "$AGENT_ENV" <<EOF
# Generated by enroll-agent.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
OSEYE_GRPC_ADDR=${SERVER_HOST}:${GRPC_PORT}
OSEYE_TLS_CERT=${CERTS_DIR}/agent.crt
OSEYE_TLS_KEY=${CERTS_DIR}/agent.key
OSEYE_TLS_CA=${CERTS_DIR}/ca.crt
OSEYE_AGENT_ID=${OSEYE_AGENT_ID}
OSEYE_BUFFER_PATH=/var/lib/oseye/buffer.db
OSEYE_MAX_CPU_PCT=4.0
OSEYE_MAX_MEM_MB=256
OSEYE_BATCH_SIZE=1000
OSEYE_BATCH_TIMEOUT_MS=1000
OSEYE_FANOTIFY_PATHS=/etc/passwd,/etc/shadow,/root/.ssh
OSEYE_INOTIFY_WATCHES=[{"path":"/tmp","recursive":false,"mask":4095}]
EOF
chmod 600 "$AGENT_ENV"

# ── Step 5: Start service ─────────────────────────────────────────────────────
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl enable --now oseye-agent
    echo ""
    echo "==> oseye-agent started."
    systemctl --no-pager status oseye-agent || true
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║           Agent Enrollment Complete                       ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║ Certs    : $CERTS_DIR/"
echo "║ Env file : $AGENT_ENV"
echo "║ Agent ID : $OSEYE_AGENT_ID"
echo "║ Server   : $SERVER_HOST:$GRPC_PORT (gRPC)"
echo "╚══════════════════════════════════════════════════════════╝"
